### ISSUE TITLE
Does this package really need plotting?

### ISSUE THREAD

**Issue by pdeffebach** [AnderGray/BivariateCopulas.jl#9]
I was in need of a Copula package and I was eager to try this out. But when adding the package I got a pyimport error, which I am sorting out now. 

But it seems somewhat unnecessary. Would it be possible to split the "math" part of this package into one package and the plotting in another?

**Comment by AnderGray** [comment]
Hi @pdeffebach, thanks for the interest.

I think running the following might help:
`julia -e 'ENV["PYTHON"]=""; using Pkg; Pkg.add("Conda"); using Conda; Conda.add("matplotlib"); Pkg.add("PyCall"); Pkg.build("PyCall"); Pkg.add("PyPlot");'`

But otherwise you have a good point, the plotting and the math part could be separated. An even better idea would to use plotting recipes, so the plotting is backend independent.

**Comment by AnderGray** [comment]
With PR #14 package now uses requires.jl, and has no PyPlot dependency.

The plotting functionality can still be used by `using PyPlot`
